### ISSUE TITLE
Unknown tag 'webmentions_head'

### ISSUE THREAD

**Issue by poblabs** [aarongustafson/jekyll-webmention_io#137]
Hey there, I'm a total noob with ruby and gems, but I thought I followed everything right. It says 1 gem installed. So then when I try to add this plugin to my site, I get this:

Any help?

```
  Liquid Exception: Liquid syntax error (line 38): Unknown tag 'webmentions_head' in /_layouts/default.html
                    ------------------------------------------------
      Jekyll 4.0.0   Please append `--trace` to the `build` command
                     for any additional information or backtrace.
                    ------------------------------------------------
```

Full trace is:

```
  Liquid Exception: Liquid syntax error (line 38): Unknown tag 'webmentions_head' in /_layouts/default.html
Traceback (most recent call last):
        37: from /usr/local/bin/jekyll:23:in `<main>'
        36: from /usr/local/bin/jekyll:23:in `load'
        35: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        34: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        33: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        32: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        31: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        30: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        29: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        28: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        27: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
        26: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
        25: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
        24: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
        23: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
        22: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
        21: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:201:in `render'
        20: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `render_docs'
        19: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `each_value'
        18: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `block in render_docs'
        17: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `each'
        16: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:509:in `block (2 levels) in render_docs'
        15: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
        14: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
        13: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:89:in `render_document'
        12: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:159:in `place_in_layouts'
        11: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:196:in `render_layout'
        10: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:122:in `render_liquid'
         9: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
         8: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
         7: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
         6: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:116:in `parse'
         5: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'
         4: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'
         3: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'
         2: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:32:in `parse'
         1: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:11:in `block in parse'
/var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (line 38): Unknown tag 'webmentions_head' (Liquid::SyntaxError)
```

**Comment by aarongustafson** [comment]
Can you post your gem list?

**Comment by poblabs** [comment]
Sure thing

```
$ gem list

*** LOCAL GEMS ***

activesupport (6.0.2.1)
addressable (2.7.0)
bigdecimal (default: 1.3.4)
bundler (2.1.4, default: 1.17.3)
cmath (default: 1.0.0)
colorator (1.1.0)
concurrent-ruby (1.1.6)
csv (default: 1.0.0)
date (default: 1.0.0)
dbm (default: 1.0.0)
did_you_mean (1.2.0)
em-websocket (0.5.1)
etc (default: 1.0.0)
eventmachine (1.2.7)
execjs (2.7.0)
fcntl (default: 1.0.0)
ffi (1.12.2)
fiddle (default: 1.0.0)
fileutils (default: 1.0.2)
forwardable-extended (2.6.0)
gdbm (default: 2.0.0)
gemoji (3.0.1)
htmlbeautifier (1.3.1)
http_parser.rb (0.6.0)
httparty (0.15.7)
i18n (1.8.2, 0.9.5)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
jekyll (4.0.0, 3.8.6)
jekyll-feed (0.13.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (2.1.0, 1.5.2)
jekyll-seo-tag (2.6.1)
jekyll-sitemap (1.4.0)
jekyll-watch (2.2.1)
jekyll-webmention_io (3.3.5)
json (2.3.0, default: 2.1.0)
kramdown (2.1.0, 1.17.0)
kramdown-parser-gfm (1.1.0)
link_header (0.0.8)
liquid (4.0.3)
listen (3.2.1)
mercenary (0.3.6)
mini_portile2 (2.4.0)
minima (2.5.1)
minitest (5.14.0, 5.10.3)
multi_xml (0.6.0)
net-telnet (0.1.1)
nokogiri (1.10.9)
openssl (2.1.2, default: 2.1.1, 2.0.9)
paint (0.8.6)
pathutil (0.16.2)
power_assert (0.2.7)
psych (default: 3.0.2)
public_suffix (4.0.3)
rake (12.3.1)
rb-fsevent (0.10.3)
rb-inotify (0.10.1)
rdoc (default: 6.0.1)
rouge (3.17.0)
rubygems-update (3.1.2, 3.0.6)
safe_yaml (1.0.5)
sass (3.7.4)
sass-listen (4.0.0)
sassc (2.2.1)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
string_inflection (0.1.2)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
terminal-table (1.8.0)
test-unit (3.2.5)
thread_safe (0.3.6)
trollop (2.0)
tzinfo (1.2.6)
uglifier (4.2.0)
unicode-display_width (1.6.1)
webmention (0.1.6)
webrick (default: 1.4.2)
zeitwerk (2.2.2)
zlib (default: 1.0.0)
```

**Comment by aarongustafson** [comment]
Do you have the gem listed in your site’s Gemfile too?

**Comment by poblabs** [comment]
Yes I do

```
$ cat Gemfile
source "http://rubygems.org"

gem "jekyll"

group :jekyll_plugins do
  gem "jekyll-webmention_io"
end
```

and in my `_confif.yml` I have this:

```
gems:
  - jekyll-webmention_io

webmentions:
  username: obrienlabs.net
  cache_bad_uris_for: 5
  js: true
```

**Comment by aarongustafson** [comment]
Hmm, weird. Is your repo somewhere I can grab it to take a look?

**Comment by poblabs** [comment]
No, it's offline. I've been using this command to build the site adhoc:

```
#!/bin/bash

# Build site
/usr/local/bin/jekyll build --source /home/obrienlabs/jekyll-websites/obrienlabs/jekyll --destination /var/www/html/obrienlabs/
```

I can attach anything that you think would help?

**Comment by poblabs** [comment]
I will say that installing the gem using `gem install jekyll-webmention_io` gave me quite a few headaches. I ended up having to use these commands and it seemed to have worked. 

```
sudo apt-get install libz-dev libiconv-hook1 libiconv-hook-dev
sudo apt-get install libssl-dev libreadline-dev libgdbm-dev
```

I'm on Ubuntu 18.04

**Comment by aarongustafson** [comment]
@poblabs I am honestly at a loss, but I suspect the gem is not installed properly (or not instantiated properly in jekyll). In my site `_config.yml`, I do not have it in my gems section. Which Jekyll version are you using? I’m on 3.6.x.

**Comment by poblabs** [comment]
Jekyll 4.0.0. Any tips on how to remove and reinstall? I can post traces if it goes south. Sadly I'm a gem noob and am learning with every command I type in.

**Comment by poblabs** [comment]
@aarongustafson I moved it from the `_config.yml` gem section to plugin section and the trace shows this:

```
  Dependency Error: Yikes! It looks like you don't have jekyll-webmention_io or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll-webmention_io gem in your Gemfile as well. The full error message from Ruby is: 'Unable to activate jekyll-webmention_io-3.3.5, because jekyll-4.0.0 conflicts with jekyll (>= 3.2.0, < 4.0)' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!
                    ------------------------------------------------
      Jekyll 4.0.0   Please append `--trace` to the `build` command
                     for any additional information or backtrace.
                    ------------------------------------------------
```

Looks like it's being blocked because of a version conflict?

**Comment by aarongustafson** [comment]
I have not made it Jekyll 4 compliant yet as I have not migrated my own site. I think some other folks were working on that though. @nhoizey you were working on it at one point, right?

**Comment by poblabs** [comment]
I guess for giggles, what [if I change this line to 5.0 instead of 4.0](https://github.com/aarongustafson/jekyll-webmention_io/blob/master/jekyll-webmention_io.gemspec#L41)? Is there a way to run this gem from the git source?

**Comment by aarongustafson** [comment]
You can run the gem from a local source by pointing it to a local folder. The gem was originally made for 3.x.

**Comment by poblabs** [comment]
Ok, I'll play with it but I doubt I'll make headway. Suppose I'll wait and see if @nhoizey has any updates.

**Comment by poblabs** [comment]
Closing in favor of #130

**Comment by poblabs** [comment]
Re-opening. Still unsure why I'm so stuck. Here's my latest attempt:

`sudo su` to elevate to root

```
# cat Gemfile
gem 'jekyll-webmention_io', :git => 'https://github.com/nhoizey/jekyll-webmention_io.git', :branch => 'nhoizey-jekyll4'
```

Let's clean things up:

```
# bundle remove jekyll-webmention_io
Removing gems from /jekyll/Gemfile
jekyll-webmention_io was removed.
```

Verify it's gone:

```
# bundle info jekyll-webmention_io
Could not find gem 'jekyll-webmention_io'.

# gem list | grep jekyll
jekyll (4.0.0, 3.8.6)
jekyll-feed (0.13.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (2.1.0, 1.5.2)
jekyll-seo-tag (2.6.1)
jekyll-sitemap (1.4.0)
jekyll-watch (2.2.1)
```


Now that it's gone, try to install again (still as root user):

```
# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching https://github.com/nhoizey/jekyll-webmention_io.git
Fetching gem metadata from http://rubygems.org/..........
Fetching gem metadata from http://rubygems.org/.
Resolving dependencies...
Using public_suffix 4.0.3
Using addressable 2.7.0
Using bundler 2.1.4
Using colorator 1.1.0
Using concurrent-ruby 1.1.6
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using execjs 2.7.0
Using ffi 1.12.2
Using forwardable-extended 2.6.0
Using htmlbeautifier 1.3.1
Using multi_xml 0.6.0
Using httparty 0.15.7
Using i18n 1.8.2
Using sassc 2.2.1
Using jekyll-sass-converter 2.1.0
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.1
Using listen 3.2.1
Using jekyll-watch 2.2.1
Using kramdown 2.1.0
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.3
Using mercenary 0.3.6
Using pathutil 0.16.2
Using rouge 3.17.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Using jekyll 4.0.0
Using json 2.3.0
Using openssl 2.1.2
Using string_inflection 0.1.2
Using uglifier 4.2.0
Using link_header 0.0.8
Using mini_portile2 2.4.0
Using nokogiri 1.10.9
Using webmention 0.1.6
Using jekyll-webmention_io 3.3.5 from https://github.com/nhoizey/jekyll-webmention_io.git (at nhoizey-jekyll4@ab70359)
Bundle complete! 1 Gemfile dependency, 40 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

It doesn't show up in the list of gems though:

```
 gem list | grep jekyll
jekyll (4.0.0, 3.8.6)
jekyll-feed (0.13.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (2.1.0, 1.5.2)
jekyll-seo-tag (2.6.1)
jekyll-sitemap (1.4.0)
jekyll-watch (2.2.1)
```

But it does have info to show:

```
#  bundle info jekyll-webmention_io
  * jekyll-webmention_io (3.3.5 ab70359)
        Summary: A Jekyll plugin for sending & receiving webmentions via Webmention.io.
        Homepage: https://github.com/aarongustafson/jekyll-webmention_io
        Path: /var/lib/gems/2.5.0/bundler/gems/jekyll-webmention_io-ab703591929a
```

Still unable to build the site after all of this

```
  Liquid Exception: Liquid syntax error (line 17): Unknown tag 'webmentions_head' in /_layouts/default.html
Traceback (most recent call last):
        37: from /usr/local/bin/jekyll:23:in `<main>'
        36: from /usr/local/bin/jekyll:23:in `load'
        35: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        34: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        33: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        32: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        31: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        30: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        29: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        28: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        27: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
        26: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
        25: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
        24: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
        23: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
        22: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
        21: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:201:in `render'
        20: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `render_docs'
        19: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:507:in `each_value'
        18: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `block in render_docs'
        17: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:508:in `each'
        16: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:509:in `block (2 levels) in render_docs'
        15: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
        14: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
        13: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:89:in `render_document'
        12: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:159:in `place_in_layouts'
        11: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:196:in `render_layout'
        10: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:122:in `render_liquid'
         9: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
         8: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:60:in `measure_time'
         7: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
         6: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:116:in `parse'
         5: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'
         4: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'
         3: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'
         2: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:32:in `parse'
         1: from /var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:11:in `block in parse'
/var/lib/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/document.rb:23:in `unknown_tag': Liquid syntax error (line 17): Unknown tag 'webmentions_head' (Liquid::SyntaxError)
```

**Comment by danielpietzsch** [comment]
Sorry, [over in the other issue](https://github.com/aarongustafson/jekyll-webmention_io/issues/130#issuecomment-607926633) I meant to say _not_ to install as root.

**Comment by poblabs** [comment]
@danielpietzsch No problem. If I try it as my local user I get some errors:

```
$ bundle install
Following files may not be writable, so sudo is needed:
  /usr/local/bin
  /var/lib/gems/2.5.0
  /var/lib/gems/2.5.0/build_info
  /var/lib/gems/2.5.0/bundler
  /var/lib/gems/2.5.0/cache
  /var/lib/gems/2.5.0/doc
  /var/lib/gems/2.5.0/extensions
  /var/lib/gems/2.5.0/gems
  /var/lib/gems/2.5.0/specifications
Using public_suffix 4.0.3
Using addressable 2.7.0
Using bundler 2.1.4
Using colorator 1.1.0
Using concurrent-ruby 1.1.6
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using em-websocket 0.5.1
Using execjs 2.7.0
Using ffi 1.12.2
Using forwardable-extended 2.6.0
Using htmlbeautifier 1.3.1
Using multi_xml 0.6.0
Using httparty 0.15.7
Using i18n 1.8.2
Using sassc 2.2.1
Using jekyll-sass-converter 2.1.0
Using rb-fsevent 0.10.3
Using rb-inotify 0.10.1
Using listen 3.2.1
Using jekyll-watch 2.2.1
Using kramdown 2.1.0
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.3
Using mercenary 0.3.6
Using pathutil 0.16.2
Using rouge 3.17.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.7.0
Using terminal-table 1.8.0
Using jekyll 4.0.0
Using json 2.3.0
Using openssl 2.1.2
Using string_inflection 0.1.2
Using uglifier 4.2.0
Using link_header 0.0.8
Using mini_portile2 2.4.0
Using nokogiri 1.10.9
Using webmention 0.1.6
Using jekyll-webmention_io 3.3.5 from https://github.com/nhoizey/jekyll-webmention_io.git (at nhoizey-jekyll4@ab70359)
Bundle complete! 1 Gemfile dependency, 40 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by leecalvink** [comment]
Looks fine to me. Are you still having issues? You were installing gems system-wide before as opposed to your user account now. Does running bundler still give the unknown tag error? Don't forget to put your user gem folder in your PATH.

**Comment by poblabs** [comment]
@leecalvink Yeah still can't get it to work. bundler doesn't give m the unknown tag, but the jekyll build Liquid generator does. 

Adding my user gem folder to the PATH does seem to help though I'm getting a new error. 

```
Traceback (most recent call last):
        20: from /usr/local/bin/jekyll:23:in `<main>'
        19: from /usr/local/bin/jekyll:23:in `load'
        18: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
        17: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        16: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        15: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        14: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        13: from /var/lib/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        12: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        11: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
        10: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
         9: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
         8: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
         7: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
         6: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
         5: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:75:in `process'
         4: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `generate'
         3: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:183:in `each'
         2: from /var/lib/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:185:in `block in generate'
         1: from /home/drsprite/jekyll-websites/obrienlabs/jekyll/_plugins/webmention_io.rb:27:in `generate'
/home/drsprite/jekyll-websites/obrienlabs/jekyll/_plugins/webmention_io.rb:44:in `update_mentions': undefined method `each' for nil:NilClass (NoMethodError)
```

**Comment by leecalvink** [comment]
Weird. That indeed looks like something wrong with the plugin. It looks like you are using a rb file instead of a gem? I'm assuming the file contents are up to date with the current gem?

**Comment by aarongustafson** [comment]
I kept having Ruby/Jekyll issues when upgrading my Mac, so I have moved off of Jekyll and will not be working on this project anymore, going forward. I am going to flag this as won’t fix, but leave it open in case someone else wants to pick up the project from here.
