### ISSUE TITLE
Getting OpenSSL error when trying to run bundle install

### ISSUE THREAD

**Issue by kylereddoch** [aarongustafson/jekyll-webmention_io#165]
I have run through your Quickstart Guide and here is what I have done.

### Gemfile:
Added the webmention_io gem
```
gem 'jekyll-webmention_io'
```

### config_.yml:
Added jekyll-webmention_io to my plugins section.
```
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-sitemap, jekyll-webmention_io]
```

But, when I try to run ```bundle install```, the following happens, resulting in an OpenSSL error. I do have OpenSSL 3.1.0 installed.

Any help would be appreciated. 🙏🏼

```
bundle install
Ignoring bigdecimal-3.1.2 because its extensions are not built. Try: gem pristine bigdecimal --version 3.1.2
Ignoring date-3.2.2 because its extensions are not built. Try: gem pristine date --version 3.2.2
Ignoring dbm-1.1.0 because its extensions are not built. Try: gem pristine dbm --version 1.1.0
Ignoring etc-1.3.0 because its extensions are not built. Try: gem pristine etc --version 1.3.0
Ignoring fcntl-1.0.1 because its extensions are not built. Try: gem pristine fcntl --version 1.0.1
Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
Ignoring fiddle-1.1.0 because its extensions are not built. Try: gem pristine fiddle --version 1.1.0
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring io-console-0.5.11 because its extensions are not built. Try: gem pristine io-console --version 0.5.11
Ignoring json-2.6.1 because its extensions are not built. Try: gem pristine json --version 2.6.1
Ignoring libxml-ruby-3.2.2 because its extensions are not built. Try: gem pristine libxml-ruby --version 3.2.2
Ignoring patron-0.13.3 because its extensions are not built. Try: gem pristine patron --version 0.13.3
Ignoring sassc-2.4.0 because its extensions are not built. Try: gem pristine sassc --version 2.4.0
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies....
Using concurrent-ruby 1.1.10
Using minitest 5.15.0
Using thread_safe 0.3.6
Using public_suffix 4.0.7
Using bundler 2.3.17
Using colorator 1.1.0
Using execjs 2.8.1
Using coffee-script-source 1.11.1
Using zeitwerk 2.5.4
Following files may not be writable, so sudo is needed:
  /Library/Ruby/Gems/2.6.0
  /Library/Ruby/Gems/2.6.0/build_info
  /Library/Ruby/Gems/2.6.0/cache
  /Library/Ruby/Gems/2.6.0/doc
  /Library/Ruby/Gems/2.6.0/extensions
  /Library/Ruby/Gems/2.6.0/gems
  /Library/Ruby/Gems/2.6.0/specifications
Using unf_ext 0.0.8.1
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using ffi 1.15.5
Using faraday-em_http 1.0.0
Using faraday-em_synchrony 1.0.0
Using commonmarker 0.23.4
Using faraday-excon 1.1.0
Using faraday-net_http 1.0.1
Using faraday-net_http_persistent 1.2.0
Using faraday-patron 1.0.0
Using faraday-httpclient 1.0.1
Using faraday-retry 1.0.3
Using ruby2_keywords 0.0.5
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using rb-fsevent 0.11.1
Using liquid 4.0.3
Using mercenary 0.3.6
Using rouge 3.26.0
Using safe_yaml 1.0.5
Using racc 1.6.0
Using jekyll-paginate 1.1.0
Using rubyzip 2.3.2
Using unicode-display_width 1.8.0
Using htmlbeautifier 1.4.2
Using multi_xml 0.6.0
Using ipaddr 1.2.5
Using json 2.6.3
Using string_inflection 0.1.2
Using link_header 0.0.8
Using i18n 0.9.5
Using unf 0.1.4
Using em-websocket 0.5.3
Using rexml 3.2.5
Using ethon 0.15.0
Using multipart-post 2.1.1
Using jekyll-commonmark 1.4.0
Using tzinfo 1.2.9
Using faraday-rack 1.0.0
Using typhoeus 1.4.0
Using nokogiri 1.13.4 (x86_64-darwin)
Using terminal-table 1.8.0
Using httparty 0.15.7
Using pathutil 0.16.2
Using activesupport 6.0.4.7
Using faraday-multipart 1.0.3
Using faraday 1.10.0
Using html-pipeline 2.14.1
Using uglifier 4.2.0
Using webmention 0.1.6
Using kramdown 2.3.2
Using jekyll-swiss 1.0.0
Using simpleidn 0.2.1
Using addressable 2.8.0
Using rb-inotify 0.10.1
Using coffee-script 2.4.1
Using dnsruby 1.61.9
Using sawyer 0.8.2
Using kramdown-parser-gfm 1.1.0
Using octokit 4.22.0
Using sass-listen 4.0.0
Using listen 3.7.1
Using jekyll-coffeescript 1.1.1
Using github-pages-health-check 1.17.9
Using sass 3.7.4
Using jekyll-watch 2.2.1
Using jekyll-sass-converter 1.5.2
Using jekyll-gist 1.5.0
Using jekyll 3.9.2
Using jekyll-avatar 0.7.0
Using jekyll-commonmark-ghpages 0.2.0
Using jekyll-default-layout 0.1.4
Using jekyll-redirect-from 0.16.0
Using jekyll-relative-links 0.6.1
Using jekyll-include-cache 0.2.1
Using jekyll-readme-index 0.3.0
Using jekyll-sitemap 1.4.0
Using jekyll-feed 0.15.1
Using jemoji 0.12.0
Using jekyll-github-metadata 2.13.0
Using jekyll-optional-front-matter 0.3.2
Using jekyll-seo-tag 2.8.0
Using jekyll-mentions 1.6.0
Using jekyll-titles-from-headings 0.5.3
Using jekyll-theme-architect 0.2.0
Using jekyll-theme-midnight 0.2.0
Using jekyll-theme-minimal 0.2.0
Using jekyll-theme-modernist 0.2.0
Using jekyll-theme-primer 0.6.0
Using jekyll-theme-slate 0.2.0
Using jekyll-theme-tactile 0.2.0
Using jekyll-theme-time-machine 0.2.0
Using minima 2.5.1
Using type-on-strap 2.4.4 from source at `.`
Using jekyll-remote-theme 0.4.3
Using jekyll-theme-merlot 0.2.0
Using jekyll-theme-cayman 0.2.0
Using jekyll-theme-dinky 0.2.0
Using jekyll-theme-hacker 0.2.0
Using jekyll-theme-leap-day 0.2.0
Using github-pages 226
Installing openssl 2.2.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/private/var/folders/h9/rxzgqqyx4kx3xxr5xvpzrpgr0000gn/T/bundler20230202-54663-xgk7jgopenssl-2.2.3/gems/openssl-2.2.3/ext/openssl
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
-r ./siteconf20230202-54663-1fty66t.rb extconf.rb
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for openssl/ssl.h... yes
checking for CRYPTO_malloc() in -lcrypto... yes
checking for SSL_new() in -lssl... yes
checking for LIBRESSL_VERSION_NUMBER in openssl/opensslv.h... no
checking for OpenSSL version >= 1.0.1 and < 3.0.0... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
        --with-openssl-dir
        --with-openssl-include
        --without-openssl-include=${openssl-dir}/include
        --with-openssl-lib
        --without-openssl-lib=${openssl-dir}/lib
        --with-kerberos-dir
        --without-kerberos-dir
        --with-kerberos-include
        --without-kerberos-include=${kerberos-dir}/include
        --with-kerberos-lib
        --without-kerberos-lib=${kerberos-dir}/lib
        --with-debug
        --without-debug
        --enable-debug
        --disable-debug
        --with-nsllib
        --without-nsllib
        --with-socketlib
        --without-socketlib
        --with-cryptolib
        --without-cryptolib
        --with-ssllib
        --without-ssllib
extconf.rb:113:in `<main>': OpenSSL >= 1.0.1, < 3.0.0 or LibreSSL >= 2.5.0 is required (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

/var/folders/h9/rxzgqqyx4kx3xxr5xvpzrpgr0000gn/T/bundler20230202-54663-xgk7jgopenssl-2.2.3/extensions/universal-darwin-22/2.6.0/openssl-2.2.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/folders/h9/rxzgqqyx4kx3xxr5xvpzrpgr0000gn/T/bundler20230202-54663-xgk7jgopenssl-2.2.3/gems/openssl-2.2.3
for inspection.
Results logged to
/var/folders/h9/rxzgqqyx4kx3xxr5xvpzrpgr0000gn/T/bundler20230202-54663-xgk7jgopenssl-2.2.3/extensions/universal-darwin-22/2.6.0/openssl-2.2.3/gem_make.out

  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:99:in `run'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/tempfile.rb:295:in `open'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in `build'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:185:in `block in build_extension'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:181:in `build_extension'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:229:in `block in build_extensions'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `each'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/ext/builder.rb:226:in `build_extensions'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/installer.rb:830:in `build_extensions'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/source/rubygems.rb:209:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/worker.rb:62:in `apply_func'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/worker.rb:57:in `block in process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/worker.rb:54:in `loop'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/worker.rb:54:in `process_queue'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.17/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing openssl (2.2.3), and Bundler cannot continue.

In Gemfile:
  jekyll-webmention_io was resolved to 3.3.5, which depends on
    openssl
```

**Comment by fancypantalons** [comment]
Any chance you're running on a fairly new version of Debian?  A little while back they moved to openssl 3.0 removed 2.x entirely, and that broke the gem.

I pushed a fix to the main repository back in November but my life has been... overwhelming... and I haven't managed cut a new release yet (which would be 3.3.7).

To test, try pulling the main version from the gem by setting your Gemfile line to:

gem "jekyll-webmention_io", git: "https://github.com/aarongustafson/jekyll-webmention_io.git"

And see what happens.

**Comment by kylereddoch** [comment]
My site is running via Github pages, not sure if that changes anything. I'll check what you suggest and see if it works.

**Comment by aarongustafson** [comment]
If I remember correctly, Jekyll plugins (apart from sanctioned ones) don’t work in GitHub pages.

**Comment by fancypantalons** [comment]
And just quickly answering the question above, yeah, a "bundle install" after that will do the job.  But as @aarongustafson points out, the plugin isn't listed among GH's whitelisted set of plugins that can be run on GitHub pages.

**Comment by kylereddoch** [comment]
> Any chance you're running on a fairly new version of Debian (or a derivative)?  A little while back they moved to openssl 3.0 and removed 2.x entirely, and that broke the gem.
> 
> 
> 
> I pushed a fix to the main repository back in November but my life has been... overwhelming... and I haven't managed cut a new release yet (which would be 3.3.7).
> 
> 
> 
> To test, try pulling the main version from the gem by setting your Gemfile line to:
> 
> 
> 
> gem "jekyll-webmention_io", git: "https://github.com/aarongustafson/jekyll-webmention_io.git"
> 
> 
> 
> And see what happens.

Okay, after adding this to my gem file and having to update my ruby version, I finally got bundle install to work. Thanks for the help. 

FYI - I noticed y'all are looking for someone to take over sponsorship of this project. I am more than willing to do so I am running g Jekyll.

**Comment by fancypantalons** [comment]
In principle I've taken over running this project (after a bunch of disconnects on my side, Aaron was able to pass on control of the RubyGems project to me, so I can issue updates), but if it wasn't obvious, I'm just doing an incredibly bad job at actually committing time to this... ;)

**Comment by kylereddoch** [comment]
Ah okay. Cool. At least someone is somewhat taking care of it. 😉

**Comment by fancypantalons** [comment]
Finally cut 3.3.7 so closing this as fixed!
