### ISSUE TITLE
Jekyll isn’t finding the gem when bundled from RubyGems

### ISSUE THREAD

**Issue by aarongustafson** [aarongustafson/jekyll-webmention_io#22]
Oddly, if I specify a path to the gem locally in the `Gemfile` it works:

```
group :jekyll_plugins do
  gem 'jekyll-feed', '~> 0.6'
  gem 'jekyll-webmention_io', :path => '/Users/aarongu/Dropbox/Code/jekyll-webmention_io'
end
```

I am sure it’s a simple fix and exhaustion is keeping it just out of reach, but I’m hitting a point of diminishing returns here and cannot seem to get it to work when I bundle in the normal way:

```
group :jekyll_plugins do
  gem 'jekyll-feed', '~> 0.6'
  gem 'jekyll-webmention_io'
end
``` 

When I do, I get the dreaded "Yikes!" error

```
bundle exec jekyll build --trace
Configuration file: /Users/aarongu/Dropbox/Sites/test-site/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-webmention_io or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-webmention_io' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
bundler: failed to load command: jekyll (/Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/bin/jekyll)
Jekyll::Errors::MissingDependencyException: jekyll-webmention_io
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/external.rb:66:in `rescue in block in require_with_graceful_fail'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/external.rb:54:in `block in require_with_graceful_fail'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/external.rb:53:in `each'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/external.rb:53:in `require_with_graceful_fail'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/plugin_manager.rb:28:in `require_gems'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/plugin_manager.rb:20:in `conscientious_require'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:115:in `setup'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/site.rb:34:in `initialize'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/commands/build.rb:28:in `new'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/commands/build.rb:28:in `process'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/gems/jekyll-3.5.0/exe/jekyll:13:in `<top (required)>'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/bin/jekyll:23:in `load'
  /Users/aarongu/Dropbox/Sites/test-site/vendor/bundle/ruby/2.4.0/bin/jekyll:23:in `<top (required)>'
```

This is with Jekyll 3.4.x and 3.5. Included the plugin in the `_config.yml` file as follows:

```
plugins:
  - jekyll-feed
  - jekyll-webmention_io
```

Without it here, the tag is not recognized at all.

Note: I’ve also tried bundling locally to `vendor/bundle` to make sure I was not hitting any other issues.

I’m posting this in hopes @alias1, @nhoizey, or anyone else who’s been involved in this and other gems might be able to help me out here.

**Comment by aarongustafson** [comment]
I think I’ve managed to capture all of the runtime dependencies in the spec. I thought that might be the issue.

**Comment by aarongustafson** [comment]
I’m wondering if the issue is OpenSSL (used for reading web pages & getting responses).

**Comment by miklb** [comment]
@aarongustafson I vaguely recall having an issue with OpenSSL and Ruby so you may be on right track. I do not recall what I had to do to resolve it however.

**Comment by alias1** [comment]
What output (if any) are you getting after running 'bundle install'?

**Comment by nhoizey** [comment]
@aarongustafson if Jekyll can't find or load the gem, why would it be related to OpenSSL, which is used by the gem?

**Comment by aarongustafson** [comment]
I figured it out. Seems it was not liking anything being outside the lib folder (despite me adding those files to the gem).

**Comment by nhoizey** [comment]
Great news!
