### ISSUE TITLE
[2.6.2] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#53]
Using Jekyll 3.5.1 and jekyll-webmention_io 2.6.2, I get this error when trying to build:

```
NoMethodError: undefined method `[]' for nil:NilClass
```

With `--trace`, I get this:

```
bundler: failed to load command: jekyll (/Users/nhoizey/.rvm/gems/ruby-2.4.0/bin/jekyll)
NoMethodError: undefined method `[]' for nil:NilClass
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-webmention_io-2.6.2/lib/jekyll/generators/gather_webmentions.rb:15:in `generate'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:178:in `block in generate'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:176:in `each'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:176:in `generate'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:72:in `process'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/command.rb:26:in `process_site'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:63:in `build'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:34:in `process'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/exe/jekyll:13:in `<top (required)>'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `load'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `<top (required)>'
```

I don't know if it's a duplicate of #46 or #47 

[Line 15 of `gather_webmentions.rb`](https://github.com/aarongustafson/jekyll-webmention_io/blob/master/lib/jekyll/generators/gather_webmentions.rb#L15) is:

```
if site.config['webmentions']['pause_lookups'] == true
```

My `_config.yml` contains this:

```
webmention:
  username: nicolas-hoizey.com
  cache_bad_uris_for: 5
  legacy_domains:
    - http://nicolas-hoizey.com
    - http://www.nicolas-hoizey.com
```

I have the exact same issue if I add `pause_lookups: true`.

**Comment by aarongustafson** [comment]
I'll take a look shortly.

**Comment by nhoizey** [comment]
Thanks. No need to hurry… ;-)

**Comment by aarongustafson** [comment]
How comfortable are you with making this plugin require Ruby >= 2.3?

**Comment by nhoizey** [comment]
I think I'm currently using Ruby 2.4

```bash
$ruby --version
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```

**Comment by aarongustafson** [comment]
Ok, I made some revisions on my end and have run through tests against my dummy Jekyll install and all looks good. Can you pull the latest form master and test locally to confirm everything is working as expected before I release it?

I’ve DRY-ed up the template extraction code and switched to safer lookups. In my testing it looks good, but until I get testing code in place (which is on my plate for the next few weeks), I would appreciate some outside validation.

**Comment by nhoizey** [comment]
@aarongustafson it works, congrats!

I just have a webmention that doesn't show anything with the default template:
https://nicolas-hoizey.com/2017/07/so-long-disqus-hello-webmentions.html#webmention-447800

**Comment by aarongustafson** [comment]
Cool. Can you file a separate bug for that? Maybe with a copy of the .yml
file and I'll being used so I can diagnose?

**Comment by nhoizey** [comment]
Of course! Done: #54
