### ISSUE TITLE
Error when building: "NoMethodError: undefined method `empty?' for nil:NilClass"

### ISSUE THREAD

**Issue by nhoizey** [aarongustafson/jekyll-webmention_io#65]
Updated to current master, I can't built the site anymore, with this error in `gather_webmentions.rb`:

```
Configuration file: /Users/nhoizey/Dropbox/Personnel/Devs/nicolas-hoizey.com/_config.yml
Configuration file: _config.yml
Configuration file: _config_credentials.yml
            Source: /Users/nhoizey/Dropbox/Personnel/Devs/nicolas-hoizey.com
       Destination: /Users/nhoizey/Dropbox/Personnel/Devs/nicolas-hoizey.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
[jekyll-webmention_io] Beginning to gather webmentions of your posts. This may take a while.
bundler: failed to load command: jekyll (/Users/nhoizey/.rvm/gems/ruby-2.4.0/bin/jekyll)
NoMethodError: undefined method `empty?' for nil:NilClass
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/generators/gather_webmentions.rb:244:in `block in process_webmentions'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/generators/gather_webmentions.rb:127:in `reverse_each'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/generators/gather_webmentions.rb:127:in `process_webmentions'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/generators/gather_webmentions.rb:69:in `block in generate'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/generators/gather_webmentions.rb:44:in `each'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bundler/gems/jekyll-webmention_io-ecdc71e7d530/lib/jekyll/generators/gather_webmentions.rb:44:in `generate'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:178:in `block in generate'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:176:in `each'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:176:in `generate'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/site.rb:72:in `process'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/command.rb:26:in `process_site'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:63:in `build'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:34:in `process'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/gems/jekyll-3.5.1/exe/jekyll:13:in `<top (required)>'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `load'
  /Users/nhoizey/.rvm/gems/ruby-2.4.0/bin/jekyll:22:in `<top (required)>'
```

**Comment by aarongustafson** [comment]
Mergd the PR. This is fixed in 2.8.1.
